# Generated by Django 3.0.5 on 2020-05-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200510_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(default='../static/main_avatar.jpg', upload_to='media/avatars/'),
        ),
    ]
