# Generated by Django 3.0.5 on 2020-05-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_ad_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('subject', models.CharField(default='', max_length=255)),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
