# Generated by Django 3.0.5 on 2020-05-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20200523_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='whose',
        ),
    ]
